#!/usr/bin/env python3
import requests
import json
import faker import Faker

APIHOST = "http://library.demo.local"
LOGIN = "cisco"
PASSWORD = "Cisco123!"

def getAuthToken():
    authCreds = (LOGIN, PASSWORD)
    r = requests.post(
        f"{APIHOST}/api/v1/loginViaBasic"
        auth = authCreds
    )
    if r.status_code == 200:
        return r.json()["token"]
    else: 
        raise Exception(f"Status code {r.status_code} and text {r.text}")

def addBook(book, apikey):
    r = requests.post(
    f"{APIHOST}/api/v1/books",
    headers = {
         "Content-type": "application/json",
         "X-API-key": apiKey
    },
    data=json.dumps(book)
    )
        if r.status_code == 200:
        print(f"Book {book} added.")
    else: 
        raise Exception(f"Status code {r.status_code} and text {r.text}")
apiKey = getAuthToken()    ### getting the authorization token key

//fake = Faker() 
//from faker import Faker
//f = Faker()
//f.name()
//print('my name is {}.'.format(f.name()))


fake = Faker()
for i in range(6, 105)
	fakeTitle = fake.catch_Phrase()
 	fakeAuthor = fake.name()
  	fakeISBN = fake.isbn13()
    book = {"id":i, "title":fakeTitle, "author":fakeAuthor, "isbn":fakeISBN}
	addBook(book, apiKey)
